[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]
cmds = [
  "cd backend && NODE_ENV=development npm install",
  "cd backend && npm run build"
]

[start]
cmd = "cd backend && npm start"

